---
# tasks file for create_users
- name: A more descriptive explanation on what is going on
  group:
     name: "{{ item }}"
  with_items:
     - apple
     - orange
     - strawberry
     - watermelon

- name: "Setting the username to {{ username }}"
  user:
     name: "{{ username }}"
     comment: My very first user
     shell: /bin/bash
     groups: apple,orange,strawberry,watermelon
