- hosts: server1
  become: true

  roles:
      - create_user_for_c1t3050X

- hosts: server2
  become: true

  roles:
      - create_user_for_c1t3051X

- hosts: server3
  become: true

  roles:
      - create_user_for_c1t3052X
