- hosts: server1
  become: true
  gather_facts: True

  tasks:
      - name: "Display system Details"
        debug:
          msg: "{{ansible_distribution}} {{ansible_distribution_version}}"

  roles:
      - create_users
